### ISSUE TITLE
Poll rate for changes is very slow?

### ISSUE THREAD

**Issue by SpeedingGuy** [jvandenaardweg/homebridge-homewizard-energy-socket#138]
I have an automation that triggers on the On/Off status of the energy socket. The socket is set to turn on by the homeward app during the cheapest times of the day, I use this to trigger other switches and setting in HomeKit.

But the status changes way too slow? is it polling the status once every 15 min? can we set it to every minut at least?

Thanks for your time and devotion, much appreciated!

- **Plugin Version**: 1.5.1
- **Homebridge Version**:  Homebridge v1.8.5 [UI v4.63.0] Ubuntu Jammy (22.04.5 LTS)
- **Node.js Version**:  v20.18.0
- **NPM Version**: 
- **Operating System**:  Docker

**Comment by jvandenaardweg** [comment]
There was not even polling in place for your use case.

I've just updated the plugin. It will now poll the state of an Energy Socket every second to make sure it's in sync. So your automations should now work.

Version `1.6.0` has the change, the latest version is `1.6.3` (as of this comment) which has some better debug logging. You can just press the update button from within Homebridge to update.

You should see something like this in your logs:

```
// switched my Energy Socket to ON in the Homewizard iOS app
[HomeWizard Energy Socket] [Energy Socket: Espresso Machine] ->  State polling detected change: ON
[HomeWizard Energy Socket] [Energy Socket: Espresso Machine] ->  Current On state "false", will be updated to "true"
[HomeWizard Energy Socket] [Energy Socket: Espresso Machine] ->  OutletInUse state is synced to ON

// switched it to OFF from the Homewizard iOS app
[HomeWizard Energy Socket] [Energy Socket: Espresso Machine] ->  State polling detected change: OFF
[HomeWizard Energy Socket] [Energy Socket: Espresso Machine] ->  Current On state "true", will be updated to "false"
[HomeWizard Energy Socket] [Energy Socket: Espresso Machine] ->  OutletInUse state is synced to OFF
```

**Comment by SpeedingGuy** [comment]
Thank you, much appreciated!!!
