### ISSUE TITLE
Energy usage data

### ISSUE THREAD

**Issue by danielpetrovic** [jvandenaardweg/homebridge-homewizard-energy-socket#46]
HomeKit itself does support energy usage data, it’s just not supported in the Home app. If you use the Eve app you can use this kind of data and it even supports history through Fakegato in Homebridge: https://github.com/simont77/fakegato-history

You can emulate the Eve Energy plugs, that do support Energy Usage within HomeKit.

It would be nice to at least push the Energy Usage to the supported HomeKit variables, so we can see the usage in the Eve app. Thanks for the great work so far.

**Comment by jvandenaardweg** [comment]
Hi @danielpetrovic , thanks for the suggestion! I am indeed aware of the FakeGato module to track power usage over time. I'll try to explore the implementation for this at a later time. Or feel free to submit a PR if you know how to develop plugins for HomeBridge
