### ISSUE TITLE
Support for P1 energy meter

### ISSUE THREAD

**Issue by owenselles** [jvandenaardweg/homebridge-homewizard-energy-socket#59]
Does this plugin support the Homeward P1 meter?

**Comment by jvandenaardweg** [comment]
Hi @owenselles , unfortunately no. I couldn't find a use case for the P1 Meter within HomeKit, as HomeKit offers no power usage insights, which is the main purpose of the P1 Meter.

Or do you have a use case you think is worth exploring?

**Comment by owenselles** [comment]
Was thinking of showing the current usage or something like that. Still
Hoping for the day when Apple does add power graphs

**Comment by jvandenaardweg** [comment]
Yeah hoping that too! Apple's Home App sometimes just feels too basic.
