### ISSUE TITLE
Support for Homewizard Watermeter

### ISSUE THREAD

**Issue by matbe81** [jvandenaardweg/homebridge-homewizard-energy-socket#81]
Can you extend the plugin to support the simple Homewizard Watermeter (https://homewizard-energy-api.readthedocs.io/endpoints.html#example-hwe-wtr) ?

**Comment by jvandenaardweg** [comment]
@matbe81 I don't think this is possible, as far as I know Homebridge (which uses Apple's HomeKit) do not support a device like a water meter.

This page only displays these "water" related devices to be supported:
https://developer.apple.com/documentation/homekit/hmaccessorycategory/accessory_category_types#3080302

[let HMAccessoryCategoryTypeSprinkler: String](https://developer.apple.com/documentation/homekit/hmaccessorycategorytypesprinkler)
A sprinkler system accessory.

[let HMAccessoryCategoryTypeFaucet: String](https://developer.apple.com/documentation/homekit/hmaccessorycategorytypefaucet)
A faucet accessory.

[let HMAccessoryCategoryTypeShowerHead: String](https://developer.apple.com/documentation/homekit/hmaccessorycategorytypeshowerhead)
A shower head accessory.

**Comment by matbe81** [comment]
Maybe, as you suggested, another device type can be used to expose those values like others plugin. Example: My SolarEdge use sensor & brightness as device type. Faucet, Splinkler, Showerhead, Valve, Switch or Sensor are some ideas to display the differents elements exposed by the API.

**Comment by jvandenaardweg** [comment]
Where would a water meter fit in? As far as i'm aware, it only registers water usage, nothing more. What would je expect to see within the Home app for this water meter?

**Comment by matbe81** [comment]
Information interested to be exposed are:
- Active (right now - boolean)
- Current use per minute (liter/m3)
- Total use (m3 or m3)
- Current day use (liter or m3)
- Current week use (liter or m3)
- Current month use (liter or m3)
- Current year use (liter or m3)
- Average daily use (liter or m3)
- Current index (calculated from an offset value to set at plugin config + total use)
Settings should allow to display values in liter or M3.

This will allow to setup automations like:
- notify (using the messenger homebridge plugin exposed as a switch) when today use is above average by X% to prevent leak
- notify when use during night or when absent from home (to prevent leak too)
- Set the color of a lightbulb depending on today/current week/month use (green as lower to red as larger)
- ...

WDYT?

**Comment by jvandenaardweg** [comment]
That sounds like lots of customization. 

Working on this Energy Socket plugin I noticed HomeKit does not provide lots of ways to deal with energy data and usage tracking over time. There's a fixed set of properties you can work with for a accessory type, like a Switch or a Light Bulb.

There is a way to track history data over time with this: https://github.com/simont77/fakegato-history , but reading that info can only be done within the Eve Home App.

I would suggest to create a seperate plugin for HomeBridge and try to see if you can fit your requirements in there. Unfortunatly I can't really help you with that as i'm drowning in day to day work...

**Comment by matbe81** [comment]
No problem. I understand. Thank you for your feedback :)

**Comment by matbe81** [comment]
Indeed. Good idea. But unfortunately, i'm not familiar with nodeJS nor Python :(
I run homebridge on a VM under ESXI.
